export const FILTER_CATEGORY = 'FILTER_CATEGORY';
export const FILTER_SUBCATEGORY = 'FILTER_SUBCATEGORY';
export const FILTER_PHOTO = 'FILTER_PHOTO';
export const FILTER_URGENT = 'FILTER_URGENT';
export const FILTER_CITY = 'FILTER_CITY';
export const FILTER_STATE = 'FILTER_STATE';
